background {
  monitor =
  path = ~/Pictures/wallpapers/itachi-uchiha-naruto-amoled-black-background-5k-3840x2160-4962.png
  blur_passes = 2
  blur_size = 7
  color = rgba(17, 17, 17, 0.85)
}

image {
  monitor =
  path = ~/Pictures/wallpapers/naruto-shippuden-wallpaper-18.jpg
  rounding = -1
  border_size = 2

  size = 30, 60

  position = 0, 65

  halign = center
  valign = center
}

input-field {
  monitor =
  size = 20%, 5%

  position = 0, -65
  font_family = Nerd Mono
  dots_size = 0.08
  shadow_passes = 1
  shadow_size = 1
  border_size = 2
  halign = center
  valign = center
}

# Shutdown
shape {
    monitor =
    size = 30, 30
    color = rgba(255, 60, 60, 1.0)
    rounding = -1 # circle
    border_size = 2
    border_color = rgba(255, 0, 0, 1.0)

    position = -30, 30
    halign = right
    valign = bottom

    onclick = shutdown now
}

# Restart
shape {
    monitor =
    size = 30, 30
    color = rgba(60, 60, 255, 1.0)
    rounding = -1 # circle
    border_size = 2
    border_color = rgba(0, 0, 255, 1.0)

    position = -75, 30
    halign = right
    valign = bottom

    onclick = shutdown -r now
}


label {
  monitor =
  text = $ATTEMPTS - Just another runing process - $TIME
  font_size = 12
  position = 0, 12
  valign = bottom
}

