# preload = /home/sela/Downloads/itachi-uchiha-dark-3840x2160-20031.jpg
# wallpaper = , /home/sela/Downloads/itachi-uchiha-dark-3840x2160-20031.jpg

splash = true
splash_opacity = 0.7
ipc = false

wallpaper {
	monitor = DP-1
	path = ~/Pictures/wallpapers/
	fit_mode = cover
	timeout = 15

}
