$font = Linotype Didot Bold

background {
  monitor =
  path = ~/Pictures/wallpapers/wallhaven-wqeq1p_3840x2160.png
  blur_passes = 2
  blur_size = 2
  color = rgba(17, 17, 17, 0.85)
}

# Hour
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    font_size = 200
    font_family = $font

    position = 50, 120
    halign = left
    valign = center
}

# Minute
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    font_size = 200
    font_family = $font

    position = 50, -120
    halign = left
    valign = center

    color = rgba(199, 106, 38, 1)
}

# Password
input-field {
  monitor =
  size = 20%, 5%

  font_family = $font
  placeholder_text = Arch btw...
  dots_size = 0.08
  dots_spacing = 1
  dots_text_format = 

  shadow_passes = 1
  shadow_size = 1
  outline_thickness = 2
  rounding = 5

  position = 50, 80
  halign = left
  valign = bottom

  outer_color = rgba(255, 169, 78, 0.8)
  # check_color = 
  # fail_color = 

  fade_on_empty = false
}

# Shutdown
shape {
    monitor =
    size = 30, 30
    color = rgba(199, 106, 38, 0.8)
    rounding = -1 # circle
    border_size = 2
    border_color = rgba(199, 106, 38, 1)

    position = -30, 30
    halign = right
    valign = bottom

    onclick = shutdown now
}

# Restart
shape {
    monitor =
    size = 30, 30
    color = rgba(255, 169, 78, 0.8)
    rounding = -1 # circle
    border_size = 2
    border_color = rgba(255, 169, 78, 1)

    position = -75, 30
    halign = right
    valign = bottom

    onclick = shutdown -r now
}


label {
  monitor =
  text = $ATTEMPTS - Just another runing process
  font_size = 12
  font_family = $font
  position = 0, 12
  valign = bottom
}

